alias cl='clear && date && ls -l'
alias cll='clear && date && la'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias suvim='sudo vim '
alias su='sudo su -'
alias c='code .'
alias s='npm start'
alias tuvi='ssh wouter@www.tuvok.nl'
alias start_postgres='pg_ctl -D /usr/local/var/postgres start'
